// frontend/webapp/src/App.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { clearSession, getUser } from './services/session'

const router = useRouter()
const user = ref(getUser())
const dark = ref(localStorage.getItem('tt-theme') === 'dark')
const userLabel = computed(() => user.value?.nombre || user.value?.usuario || 'Mi cuenta')
const isAdmin = computed(() => {
  const roleId = Number(user.value?.id_rol ?? user.value?.idRol ?? 0)
  const roleName = String(user.value?.rol ?? user.value?.role ?? '').toLowerCase()
  return roleId === 1 || roleName === 'admin'
})

function toggleTheme() {
  dark.value = !dark.value
  localStorage.setItem('tt-theme', dark.value ? 'dark' : 'light')
}

function logout() {
  clearSession()
  user.value = null
  router.push('/login')
}
</script>

<template>
  <div class="app-shell" :class="{ dark }">
    <header class="topbar">
      <RouterLink class="brand" to="/"><span>TT</span> TiendaTech</RouterLink>
      <nav aria-label="Navegación principal">
        <RouterLink to="/">Productos</RouterLink>
        <RouterLink to="/armado">Arma tu PC</RouterLink>
        <RouterLink to="/carrito">Carrito</RouterLink>
        <RouterLink v-if="isAdmin" to="/admin">Administración</RouterLink>
      </nav>
      <div class="actions">
        <button class="icon-button" type="button" :aria-label="dark ? 'Usar tema claro' : 'Usar tema oscuro'" @click="toggleTheme">
          {{ dark ? '☀' : '☾' }}
        </button>
        <template v-if="user"><RouterLink class="text-button" to="/cuenta">{{ userLabel }}</RouterLink><button class="text-button" type="button" @click="logout">Salir</button></template>
        <RouterLink v-else class="button small" to="/login">Ingresar</RouterLink>
      </div>
    </header>
    <main><RouterView @session-changed="user = getUser()" /></main>
    <footer>© 2026 TiendaTech · Arquitectura de microservicios</footer>
  </div>
</template>

// Apps/web/frontend/webapp/src/App.tsx
import { useEffect, useState } from 'react'
import { Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { clearSession, getUser, lastSessionActivity, markSessionActivity, SESSION_CLEARED_EVENT } from './services/session'
import AccountView from './views/AccountView'
import AdminView from './views/AdminView'
import BuilderView from './views/BuilderView'
import CartView from './views/CartView'
import CatalogView from './views/CatalogView'
import CheckoutView from './views/CheckoutView'
import InvoiceView from './views/InvoiceView'
import LoginView from './views/LoginView'
import ProductDetailView from './views/ProductDetailView'
import RecoveryView from './views/RecoveryView'
import RegisterView from './views/RegisterView'
import WorkerView from './views/WorkerView'

const isAdmin = (user: ReturnType<typeof getUser>) => Number(user?.id_rol ?? user?.idRol ?? 0) === 1 || String(user?.rol ?? user?.role ?? '').toLowerCase() === 'admin'

function AdminRoute({ children }: { children: React.ReactNode }) {
  const location = useLocation()
  return isAdmin(getUser()) ? children : <Navigate to={`/login?next=${encodeURIComponent(location.pathname)}`} replace />
}

export default function App() {
  const navigate = useNavigate()
  const [user, setUser] = useState(getUser())
  const [dark, setDark] = useState(localStorage.getItem('tt-theme') === 'dark')
  const toggleTheme = () => setDark((value) => { localStorage.setItem('tt-theme', value ? 'light' : 'dark'); return !value })
  const logout = () => { clearSession(); setUser(null); navigate('/login') }
  useEffect(() => {
    if (!user) return
    const idleLimitMs = 30 * 60 * 1000
    let timer = 0
    let lastRecorded = 0
    const expire = () => {
      clearSession()
      setUser(null)
      navigate('/login?reason=inactive', { replace: true })
    }
    const schedule = () => {
      window.clearTimeout(timer)
      const remaining = idleLimitMs - (Date.now() - lastSessionActivity())
      if (remaining <= 0) expire()
      else timer = window.setTimeout(expire, remaining)
    }
    const activity = () => {
      const now = Date.now()
      if (now - lastRecorded >= 15_000) {
        lastRecorded = now
        markSessionActivity()
        schedule()
      }
    }
    const sessionCleared = () => { setUser(null); navigate('/login', { replace: true }) }
    const events: (keyof WindowEventMap)[] = ['pointerdown', 'keydown', 'scroll', 'touchstart']
    events.forEach(event => window.addEventListener(event, activity, { passive: true }))
    window.addEventListener(SESSION_CLEARED_EVENT, sessionCleared)
    schedule()
    return () => {
      window.clearTimeout(timer)
      events.forEach(event => window.removeEventListener(event, activity))
      window.removeEventListener(SESSION_CLEARED_EVENT, sessionCleared)
    }
  }, [user, navigate])
  return <div className={`app-shell${dark ? ' dark' : ''}`}>
    <header className="topbar">
      <Link className="brand" to="/"><span>TT</span> TiendaTech</Link>
      <nav aria-label="Navegación principal"><Link to="/">Productos</Link><Link to="/armado">Arma tu PC</Link><Link to="/carrito">Carrito</Link>{isAdmin(user) && <Link to="/admin">Administración</Link>}</nav>
      <div className="actions"><button className="icon-button" type="button" aria-label={dark ? 'Usar tema claro' : 'Usar tema oscuro'} onClick={toggleTheme}>{dark ? '☀' : '☾'}</button>{user ? <><Link className="text-button" to="/cuenta">{user.nombre || user.usuario || 'Mi cuenta'}</Link><button className="text-button" type="button" onClick={logout}>Salir</button></> : <Link className="button small" to="/login">Ingresar</Link>}</div>
    </header>
    <main><Routes>
      <Route path="/" element={<CatalogView />} /><Route path="/login" element={<LoginView onSessionChanged={() => setUser(getUser())} />} /><Route path="/producto/:id" element={<ProductDetailView />} /><Route path="/carrito" element={<CartView />} />
      <Route path="/admin" element={<AdminRoute><AdminView /></AdminRoute>} /><Route path="/armado" element={<BuilderView />} /><Route path="/registro" element={<RegisterView />} /><Route path="/recuperacion" element={<RecoveryView />} />
      <Route path="/cuenta" element={<AccountView />} /><Route path="/pago" element={<CheckoutView />} /><Route path="/factura/:id?" element={<InvoiceView />} /><Route path="/trabajador" element={<WorkerView />} /><Route path="*" element={<Navigate to="/" replace />} />
    </Routes></main>
    <footer>© 2026 TiendaTech · Arquitectura de microservicios</footer>
  </div>
}
